### ISSUE TITLE
Problem adding subrole

### ISSUE THREAD

**Issue by ghost** [jamiegyoung/deal-master-bot#1]
Say the subrole is called "Subscribers" 
IF you do $rolesub @Subscribers it will not work
You HAVE to do $rolesub Subscribers

Mind adding a stanky IF statement?

**Comment by jamiegyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BlankzBB: subrole @role issue](https://trello.com/c/oPqyZzgr/1-blankzbb-subrole-role-issue)

**Comment by jamiegyoung** [comment]
Fixed a while ago
